#!/usr/bin/awk -f
# Note: on Solaris, use nawk instead
# 定义BEGIN块，在程序开始时执行
BEGIN {
	# 遍历命令行参数数组ARGV
	for (i = 0; i < ARGC; i++)
		# 打印每个参数的索引和值
		printf "ARGV[%d] = %s\n", i, ARGV[i]
	# 程序执行完毕后退出
	exit
}
